In [1]:
import numpy as np
import torch
import time
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

def are_all_equal_batched_numpy(test_images):
    reshaped = test_images.reshape(100, 5, 256, 144)
    return np.all(reshaped[:, 0:1] == reshaped[:, 1:], axis=(1, 2, 3))

def are_all_equal_batched_torch(torch_images):
    reshaped = torch_images.view(100, 5, 256, 144)
    comparisons = torch.all(reshaped[:, 0:1] == reshaped[:, 1:], dim=(2, 3))
    return torch.all(comparisons, dim=1).cpu().numpy()

# Create sample data
test_images = np.random.rand(500, 256, 144).astype(np.float32)
test_images_tensor=torch.from_numpy(test_images).to(device)
# Warm-up GPU
result_torch = are_all_equal_batched_torch(test_images_tensor)

# Benchmark
def benchmark(func, data, n_iterations=100):
    start_time = time.time()
    for _ in range(n_iterations):
        _ = func(data)
    return time.time() - start_time

numpy_time = benchmark(are_all_equal_batched_numpy, test_images)
torch_time = benchmark(are_all_equal_batched_torch, test_images_tensor)


print(f"NumPy time: {numpy_time:.4f} seconds")
print(f"PyTorch time: {torch_time:.4f} seconds, with result {result_torch}")

TypeError: all() received an invalid combination of arguments - got (Tensor, dim=tuple), but expected one of:
 * (Tensor input)
 * (Tensor input, name dim, bool keepdim, *, Tensor out)
 * (Tensor input, int dim, bool keepdim, *, Tensor out)


In [33]:
test_images = np.ones((500, 256, 144)).astype(np.float32)
test_images_tensor=torch.from_numpy(test_images).to(device)
test_images_tensor[0:15,:,:]=0

In [34]:
reshaped = test_images_tensor.view(100, 5, 256, 144)


In [35]:
reshaped.shape
reshaped_bool=reshaped[:, 0:1] == reshaped[:, 1:]

In [36]:
print(torch.all(reshaped_bool))

tensor(True, device='cuda:0')


In [10]:
reshaped_bool.shape

torch.Size([100, 4, 256, 144])

In [16]:
torch.all(reshaped_bool.flatten())

tensor(False, device='cuda:0')

In [14]:
a1=torch.all(reshaped_bool.flatten(1,-1))
print(a1.shape)

torch.Size([])


In [7]:
comparisons = torch.all(reshaped[:, 0:1] == reshaped[:, 1:], dim=(2, 3))

TypeError: all() received an invalid combination of arguments - got (Tensor, dim=tuple), but expected one of:
 * (Tensor input)
 * (Tensor input, name dim, bool keepdim, *, Tensor out)
 * (Tensor input, int dim, bool keepdim, *, Tensor out)


In [165]:
a=torch.zeros(16)
for i in range(16):
    a[i]=int(2*i)
a.view(2,2,4)

tensor([[[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.]],

        [[16., 18., 20., 22.],
         [24., 26., 28., 30.]]])

In [171]:
a=a.view(2,2,4)
b=a[:,0,0].unsqueeze(1)
a[0,0,1]=0
#print(a[0,:,:])
#print(a[:,0,:])
#print(a.shape)
print(b.shape)
print(b)
#print(a)
print(b==a[:,:,:])



torch.Size([2, 1])
tensor([[ 0.],
        [16.]])
tensor([[[ True,  True, False, False],
         [False, False, False, False]],

        [[False, False, False, False],
         [False, False, False, False]]])


In [67]:
torch.all(a[0,:]==a[1,:])

tensor(False)

In [128]:
a[:,:]+a[:,:]

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         [[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]]]])

In [126]:
import numpy as np
x=np.array([1,2,3])
y=x+1
y[0]=0
print(y,x)
#print(d.dtype)
#d[0]=[1,2,3]
# print(d)
# print(c)
# #c[:]==d[0]
# print(d[0,0])

[0 3 4] [1 2 3]


TypeError: can only concatenate list (not "int") to list